### PR TITLE
Add calev submodule

### PR DESCRIPTION
**Pull request by eikek**
Hi @fthomas , from the conversation from march, here is an attempt to add a module for integrating the calev library into fs2-cron. Let me know if that is ok with you, or if I can improve anything. Thanks!

### CODE REVIEW

**Comment by eikek** [comment]
>  [error] (githubWorkflowCheck) ci.yml does not contain contents that would have been generated by sbt-github-actions; try running githubWorkflowGenerate

I ran this regenerate task to fix the workflow file. Guess this needs now an approval to be able to run.

**Comment by fthomas** [comment]
@eikek, this looks great! Will merge and push a new release ASAP.

**Comment by fthomas** [comment]
fs2-cron-calev is now available in version 0.7.1. \o/

**Comment by eikek** [comment]
Thank you!

**Pull request merged**
